# -*- coding: utf-8 -*-
"""인공지능1_프로젝트.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IAj22thhx-PafJi2Fge9Ew5_XB4htxqU
"""

import kagglehub
import os

# LCC-FASD 다운로드
lcc_path = kagglehub.dataset_download("faber24/lcc-fasd")
print("LCC-FASD path:", lcc_path)

# 폴더 구조 출력
def show_tree(root, max_depth=3, prefix=""):
    if max_depth < 0:
        return
    try:
        entries = sorted(os.listdir(root))
    except NotADirectoryError:
        return
    for e in entries[:10]:
        full = os.path.join(root, e)
        is_dir = os.path.isdir(full)
        marker = "📁" if is_dir else "  "
        # 이미지 폴더면 개수도 표시
        if is_dir:
            n = len(os.listdir(full))
            print(f"{prefix}{marker} {e}/  ({n} items)")
            show_tree(full, max_depth - 1, prefix + "    ")
        else:
            print(f"{prefix}{marker} {e}")

show_tree(lcc_path)

import kagglehub, os

nuaa_path = kagglehub.dataset_download("aleksandrpikul222/nuaaaa")
print("NUAA path:", nuaa_path)

# 폴더 구조 출력
for root, dirs, files in os.walk(nuaa_path):
    depth = root.replace(nuaa_path, "").count(os.sep)
    if depth > 3:
        continue
    indent = "  " * depth
    imgs = [f for f in files if f.lower().endswith((".png",".jpg",".jpeg",".bmp"))]
    print(f"{indent}{os.path.basename(root)}/  ({len(imgs)} imgs)")
    for f in imgs[:5]:
        print(f"{indent}    {f}")

import os, shutil, random
from collections import defaultdict

# 경로 설정
LCC_ROOT  = os.path.join(lcc_path,  "LCC_FASD")
NUAA_ROOT = os.path.join(nuaa_path, "raw")     # ← 수정됨
OUT       = "./dataset"

# 재실행 : 기존 결과 삭제 후 새로 생성
if os.path.exists(OUT):
    shutil.rmtree(OUT)

SEED = 42
random.seed(SEED)

# 유틸
def safe_copy(src, dst):
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    try:
        os.symlink(os.path.abspath(src), dst)
    except (OSError, NotImplementedError):
        shutil.copy2(src, dst)

def collect_images(folder):
    """폴더 내 이미지 파일 경로 수집"""
    exts = {".png", ".jpg", ".jpeg", ".bmp"}
    return sorted([
        os.path.join(folder, f)
        for f in os.listdir(folder)
        if os.path.splitext(f)[1].lower() in exts
    ])

# --- STEP 1: LCC-FASD ---------------------------------------
print("=" * 50)
print("STEP 1: LCC-FASD 복사")
lcc_split_map = {
    "LCC_FASD_training":    "train",
    "LCC_FASD_development": "val",
    "LCC_FASD_evaluation":  "test",
}
lcc_cls_map = {"real": "real", "spoof": "replay"}

lcc_count = defaultdict(int)
for src_split, dst_split in lcc_split_map.items():
    for src_cls, dst_cls in lcc_cls_map.items():
        src_dir = os.path.join(LCC_ROOT, src_split, src_cls)
        for f in collect_images(src_dir):
            fname = "lcc_" + os.path.basename(f)
            safe_copy(f, os.path.join(OUT, dst_split, dst_cls, fname))
            lcc_count[(dst_split, dst_cls)] += 1

for k, v in sorted(lcc_count.items()):
    print(f"  {k[0]:5s}/{k[1]:6s}: {v}")

# ── STEP 2: NUAA (subject 단위 train:val:test = 60:20:20 split) ─
print("\nSTEP 2: NUAA subject-wise split & 복사")

nuaa_cls_map = {
    "ImposterRaw": "print",
    "ClientRaw":   "real",
}

subject_ids = sorted(os.listdir(os.path.join(NUAA_ROOT, "ImposterRaw")))
random.shuffle(subject_ids)

n = len(subject_ids)
n_train = int(n * 0.6)
n_val   = int(n * 0.2)
# 나머지는 test
split_assign = (
    {sid: "train" for sid in subject_ids[:n_train]}
    | {sid: "val"   for sid in subject_ids[n_train:n_train + n_val]}
    | {sid: "test"  for sid in subject_ids[n_train + n_val:]}
)
print(f"  subject 수: {n}  "
      f"→ train:{n_train}  val:{n_val}  test:{n - n_train - n_val}")

nuaa_count = defaultdict(int)
for raw_folder, dst_cls in nuaa_cls_map.items():
    raw_dir = os.path.join(NUAA_ROOT, raw_folder)
    for sid in os.listdir(raw_dir):
        if sid not in split_assign:
            continue
        dst_split = split_assign[sid]
        src_dir = os.path.join(raw_dir, sid)
        for f in collect_images(src_dir):
            fname = f"nuaa_{sid}_{os.path.basename(f)}"
            safe_copy(f, os.path.join(OUT, dst_split, dst_cls, fname))
            nuaa_count[(dst_split, dst_cls)] += 1

for k, v in sorted(nuaa_count.items()):
    print(f"  {k[0]:5s}/{k[1]:6s}: {v}")

# ── STEP 3: 최종 집계 ──────────────────────────────────────────
print("\n최종 dataset 구조:")
total = defaultdict(int)
for split in ["train", "val", "test"]:
    for cls in ["real", "print", "replay"]:
        d = os.path.join(OUT, split, cls)
        n_imgs = len(os.listdir(d)) if os.path.isdir(d) else 0
        total[(split, cls)] = n_imgs

print(f"{'':6s} {'real':>7s} {'print':>7s} {'replay':>7s} {'합계':>7s}")
for split in ["train", "val", "test"]:
    row = [total[(split, c)] for c in ["real", "print", "replay"]]
    print(f"{split:6s} {row[0]:>7d} {row[1]:>7d} {row[2]:>7d} {sum(row):>7d}")

"""**라이브러리 import 및 환경 설정**"""

import os, time, copy, random
from collections import Counter
import numpy as np
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, WeightedRandomSampler
from torchvision import datasets, transforms, models
from torchvision.models import EfficientNet_B0_Weights

SEED = 42
random.seed(SEED); np.random.seed(SEED)
torch.manual_seed(SEED); torch.cuda.manual_seed_all(SEED)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("PyTorch:", torch.__version__, "| Device:", device)

"""

**하이퍼파라미터 설정**"""

DATA_DIR        = "./dataset"
IMG_SIZE        = 224
BATCH_SIZE      = 32
EPOCHS          = 15
LR              = 1e-4
WEIGHT_DECAY    = 1e-4
LABEL_SMOOTHING = 0.1
NUM_WORKERS     = 2
IMBALANCE       = "sampler"     # "sampler" | "loss_weight" | "none"
WEIGHTS_PATH    = "./best_model.pth"

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD  = [0.229, 0.224, 0.225]

"""**데이터 불러오기 및 변환**"""

train_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.1),
    transforms.RandomRotation(degrees=8),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])
eval_tf = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
])

train_ds = datasets.ImageFolder(os.path.join(DATA_DIR, "train"), train_tf)
val_ds   = datasets.ImageFolder(os.path.join(DATA_DIR, "val"),   eval_tf)
test_path = os.path.join(DATA_DIR, "test")
test_ds = datasets.ImageFolder(test_path, eval_tf) if os.path.isdir(test_path) else None

classes = train_ds.classes
print("클래스 매핑:", dict(enumerate(classes)))
print("train:", len(train_ds), "| val:", len(val_ds),
      "| test:", len(test_ds) if test_ds else "없음")

"""**데이터 불균형 처리**"""

train_targets = [label for _, label in train_ds.samples]
counts = Counter(train_targets)

sampler, shuffle, class_weights_tensor = None, True, None

if IMBALANCE == "sampler":
    per_class_w = {c: 1.0/n for c, n in counts.items()}
    sample_weights = [per_class_w[t] for t in train_targets]
    sampler = WeightedRandomSampler(torch.DoubleTensor(sample_weights),
                                    len(sample_weights), replacement=True)
    shuffle = False
    print("→ WeightedRandomSampler 사용")
elif IMBALANCE == "loss_weight":
    total, n_cls = sum(counts.values()), len(counts)
    w = [total/(n_cls*counts[i]) for i in range(n_cls)]
    class_weights_tensor = torch.FloatTensor(w).to(device)
    print("→ loss weight:", {classes[i]: round(w[i],3) for i in range(n_cls)})
else:
    print("→ 불균형 처리 없음")

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, sampler=sampler,
                          shuffle=shuffle, num_workers=NUM_WORKERS, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = (DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False,
                           num_workers=NUM_WORKERS, pin_memory=True) if test_ds else None)
print("DataLoader 준비 완료")

"""**모델 설정**"""

def build_model(num_classes=3, freeze_backbone=False):
    model = models.efficientnet_b0(weights=EfficientNet_B0_Weights.IMAGENET1K_V1)
    if freeze_backbone:
        for p in model.parameters():
            p.requires_grad = False
    in_features = model.classifier[1].in_features
    model.classifier[1] = nn.Linear(in_features, num_classes)
    return model

model = build_model(num_classes=len(classes)).to(device)
criterion = nn.CrossEntropyLoss(weight=class_weights_tensor,
                                label_smoothing=LABEL_SMOOTHING)
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=WEIGHT_DECAY)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=EPOCHS)
print(model.classifier)

"""**모델 학습**"""

def run_epoch(model, loader, criterion, optimizer, train=True):
    model.train() if train else model.eval()
    total_loss, correct, total = 0.0, 0, 0
    torch.set_grad_enabled(train)
    for images, labels in loader:
        images, labels = images.to(device), labels.to(device)
        if train: optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        if train:
            loss.backward(); optimizer.step()
        total_loss += loss.item() * images.size(0)
        correct += (outputs.argmax(1) == labels).sum().item()
        total += images.size(0)
    torch.set_grad_enabled(True)
    return total_loss/total, correct/total

history = {"train_loss":[], "train_acc":[], "val_loss":[], "val_acc":[]}
best_val_acc, best_state = 0.0, copy.deepcopy(model.state_dict())

for epoch in range(1, EPOCHS+1):
    t0 = time.time()
    tr_loss, tr_acc = run_epoch(model, train_loader, criterion, optimizer, True)
    va_loss, va_acc = run_epoch(model, val_loader,   criterion, optimizer, False)
    scheduler.step()
    for k, v in zip(history, [tr_loss, tr_acc, va_loss, va_acc]):
        history[k].append(v)
    print(f"[{epoch:2d}/{EPOCHS}] train_loss={tr_loss:.4f} acc={tr_acc:.4f} | "
          f"val_loss={va_loss:.4f} acc={va_acc:.4f} | {time.time()-t0:.1f}s")
    if va_acc > best_val_acc:
        best_val_acc = va_acc
        best_state = copy.deepcopy(model.state_dict())
        torch.save({"model_state": best_state, "classes": classes,
                    "img_size": IMG_SIZE}, WEIGHTS_PATH)
        print(f"   ↑ best 갱신 (val_acc={va_acc:.4f}) → 저장")

print(f"\n학습 완료. best val_acc = {best_val_acc:.4f}")

"""**학습 추이 시각화**"""

fig, ax = plt.subplots(1, 2, figsize=(12,4))
ax[0].plot(history["train_loss"], label="train"); ax[0].plot(history["val_loss"], label="val")
ax[0].set_title("Loss"); ax[0].set_xlabel("epoch"); ax[0].legend()
ax[1].plot(history["train_acc"], label="train"); ax[1].plot(history["val_acc"], label="val")
ax[1].set_title("Accuracy"); ax[1].set_xlabel("epoch"); ax[1].legend()
plt.tight_layout(); plt.show()

"""**샘플 데이터 예측 시각화 1**"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from torchvision import transforms
from torchvision import models
import torch.nn as nn
from torchvision.models import EfficientNet_B0_Weights

# ── 0) 모델이 메모리에 없을 때를 대비하여 모델 로드 ──

if "model" not in globals():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    ckpt = torch.load("./best_model.pth", map_location=device)
    classes = ckpt["classes"]
    model = models.efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, len(classes))
    model.load_state_dict(ckpt["model_state"])
    model = model.to(device).eval()
    IMG_SIZE = ckpt["img_size"]
    eval_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

# ── 1) 예측할 이미지 경로 지정 ──────────────────────────────
import os, glob
candidates = glob.glob("./dataset/test/replay/*")
IMG_PATH = candidates[0]

# ── 2) 예측 ────────────────────────────────────────────────
img = Image.open(IMG_PATH).convert("RGB")
x = eval_tf(img).unsqueeze(0).to(device)

with torch.no_grad():
    logits = model(x)
    probs = torch.softmax(logits, dim=1)[0].cpu().numpy()

pred_idx = int(probs.argmax())
pred_label = classes[pred_idx]

# ── 3) 결과 시각화: 원본 이미지 + 클래스별 확률 막대 ──────────
fig, ax = plt.subplots(1, 2, figsize=(11, 4))

# (왼쪽) 입력 이미지 원본
ax[0].imshow(img)
ax[0].axis("off")
ax[0].set_title(f"Input image\n{os.path.basename(IMG_PATH)}", fontsize=10)

# (오른쪽) 클래스별 확률 막대그래프
colors = ["#55A868" if i == pred_idx else "#C0C0C0" for i in range(len(classes))]
ax[1].barh(classes, probs, color=colors)
ax[1].set_xlim(0, 1)
ax[1].set_xlabel("probability")
ax[1].set_title(f"Prediction: {pred_label} ({probs[pred_idx]*100:.1f}%)", fontsize=11)
for i, p in enumerate(probs):
    ax[1].text(p + 0.01, i, f"{p:.3f}", va="center", fontsize=9)
ax[1].invert_yaxis()

plt.tight_layout()
plt.show()

# ── 4) 텍스트로도 출력 ──────────────────────────────────────
print(f"파일: {IMG_PATH}")
print(f"예측: {pred_label}  (확신도 {probs[pred_idx]*100:.2f}%)")
print("클래스별 확률:")
for c, p in zip(classes, probs):
    print(f"   {c:8s}: {p:.4f}")

"""**샘플 예측 시각화 2**"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import os, glob, random
from torchvision import transforms, models
import torch.nn as nn

# ── 0) 모델이 메모리에 없을 때를 대비하여 로드 ──
if "model" not in globals():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    ckpt = torch.load("./best_model.pth", map_location=device)
    classes = ckpt["classes"]
    model = models.efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, len(classes))
    model.load_state_dict(ckpt["model_state"])
    model = model.to(device).eval()
    IMG_SIZE = ckpt["img_size"]
    eval_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

# ── 1) 각 클래스에서 1장씩 + 나머지 랜덤으로 총 5장 선택 ──
N_SAMPLES = 5
TEST_DIR = "./dataset/test"

# 각 클래스별 파일 목록 수집
class_files = {c: glob.glob(os.path.join(TEST_DIR, c, "*")) for c in classes}

picked = []  # (파일경로, 정답라벨) 튜플 리스트
# (1) 각 클래스에서 최소 1장씩 보장
for c in classes:
    f = random.choice(class_files[c])
    picked.append((f, c))

# (2) 남은 자리는 전체에서 랜덤으로 채움 (중복 방지)
all_files = [(f, c) for c in classes for f in class_files[c]]
random.shuffle(all_files)
already = set(p[0] for p in picked)
for f, c in all_files:
    if len(picked) >= N_SAMPLES:
        break
    if f not in already:
        picked.append((f, c)); already.add(f)

random.shuffle(picked)  # 표시 순서 섞기

# ── 2) 예측 + 시각화 ──────────────────────────────────────
fig, axes = plt.subplots(2, N_SAMPLES, figsize=(4 * N_SAMPLES, 8))

for col, (img_path, true_label) in enumerate(picked):
    img = Image.open(img_path).convert("RGB")
    x = eval_tf(img).unsqueeze(0).to(device)
    with torch.no_grad():
        probs = torch.softmax(model(x), dim=1)[0].cpu().numpy()
    pred_idx = int(probs.argmax())
    pred_label = classes[pred_idx]
    correct = (pred_label == true_label)

    # (위) 입력 이미지 — 맞으면 초록, 틀리면 빨강 테두리
    ax_img = axes[0, col]
    ax_img.imshow(img)
    ax_img.set_xticks([]); ax_img.set_yticks([])
    edge = "#2E8B57" if correct else "#D62728"
    for spine in ax_img.spines.values():
        spine.set_edgecolor(edge); spine.set_linewidth(4)
    mark = "✓" if correct else "✗"
    ax_img.set_title(f"GT: {true_label}\nPred: {pred_label} {mark}",
                     fontsize=11, color=edge, fontweight="bold")

    # (아래) 클래스별 확률 막대
    ax_bar = axes[1, col]
    colors = ["#55A868" if i == pred_idx else "#C0C0C0" for i in range(len(classes))]
    ax_bar.barh(classes, probs, color=colors)
    ax_bar.set_xlim(0, 1)
    ax_bar.invert_yaxis()
    for i, p in enumerate(probs):
        ax_bar.text(p + 0.02, i, f"{p:.2f}", va="center", fontsize=9)
    ax_bar.set_xlabel("prob")

plt.tight_layout()
plt.show()

# ── 3) 텍스트 요약 ────────────────────────────────────────
print("=" * 50)
n_correct = 0
for img_path, true_label in picked:
    img = Image.open(img_path).convert("RGB")
    x = eval_tf(img).unsqueeze(0).to(device)
    with torch.no_grad():
        probs = torch.softmax(model(x), dim=1)[0].cpu().numpy()
    pred = classes[int(probs.argmax())]
    ok = (pred == true_label)
    n_correct += ok
    print(f"[{'O' if ok else 'X'}] GT={true_label:7s} → Pred={pred:7s} "
          f"({probs.max()*100:.1f}%)  {os.path.basename(img_path)}")
print("=" * 50)
print(f"정확도: {n_correct}/{len(picked)}")

from google.colab import drive
drive.mount('/content/drive')

import os
SAVE_DIR = "/content/drive/MyDrive/fas_project"   # 드라이브 안 폴더
os.makedirs(SAVE_DIR, exist_ok=True)

WEIGHTS_PATH = os.path.join(SAVE_DIR, "best_model.pth")
print("모델 저장 경로:", WEIGHTS_PATH)

"""**데이터셋 현황 시각화**"""

import os, matplotlib.pyplot as plt, numpy as np

SAVE_DIR = "/content/drive/MyDrive/fas_project"
os.makedirs(SAVE_DIR, exist_ok=True)

splits = ["train", "val", "test"]
cls_order = ["real", "print", "replay"]
counts = {s: [len(os.listdir(f"./dataset/{s}/{c}")) for c in cls_order] for s in splits}

x = np.arange(len(cls_order)); w = 0.25
fig, ax = plt.subplots(figsize=(8, 5))
for i, s in enumerate(splits):
    bars = ax.bar(x + (i-1)*w, counts[s], w, label=s)
    ax.bar_label(bars, fontsize=8)
ax.set_xticks(x); ax.set_xticklabels(cls_order)
ax.set_ylabel("number of images"); ax.set_title("Class distribution per split")
ax.legend()
plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/viz1_class_dist.png", dpi=150, bbox_inches="tight")
plt.show()

import glob, random
from PIL import Image
import matplotlib.pyplot as plt

N_PER_CLASS = 4
fig, axes = plt.subplots(len(cls_order), N_PER_CLASS, figsize=(N_PER_CLASS*2.5, len(cls_order)*2.5))
for r, c in enumerate(cls_order):
    files = random.sample(glob.glob(f"./dataset/train/{c}/*"), N_PER_CLASS)
    for cc, f in enumerate(files):
        axes[r, cc].imshow(Image.open(f).convert("RGB"))
        axes[r, cc].axis("off")
        if cc == 0:
            axes[r, cc].set_ylabel(c, fontsize=12)
    axes[r, 0].set_title(c, loc="left", fontsize=12, fontweight="bold")
plt.suptitle("Sample images per class", y=1.01)
plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/viz2_samples.png", dpi=150, bbox_inches="tight")
plt.show()

import json
# 학습 직후 한 번 실행해두면 나중에 다시 안 돌려도 됨
with open(f"{SAVE_DIR}/history.json", "w") as f:
    json.dump(history, f)

"""**학습 추이 및 최종 결과 시각화**"""

import json, matplotlib.pyplot as plt
with open(f"{SAVE_DIR}/history.json") as f:
    history = json.load(f)

fig, ax = plt.subplots(1, 2, figsize=(12, 4))
ax[0].plot(history["train_loss"], marker="o", label="train")
ax[0].plot(history["val_loss"],   marker="s", label="val")
ax[0].set_title("Loss"); ax[0].set_xlabel("epoch"); ax[0].legend(); ax[0].grid(alpha=.3)
ax[1].plot(history["train_acc"], marker="o", label="train")
ax[1].plot(history["val_acc"],   marker="s", label="val")
ax[1].set_title("Accuracy"); ax[1].set_xlabel("epoch"); ax[1].legend(); ax[1].grid(alpha=.3)
plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/viz3_curves.png", dpi=150, bbox_inches="tight")
plt.show()

import matplotlib.pyplot as plt, numpy as np
from sklearn.metrics import precision_recall_fscore_support

p, r, f1, _ = precision_recall_fscore_support(y_true, y_pred, labels=range(len(classes)))
x = np.arange(len(classes)); w = 0.25
fig, ax = plt.subplots(figsize=(8, 5))
for i, (vals, name) in enumerate(zip([p, r, f1], ["precision", "recall", "f1"])):
    bars = ax.bar(x + (i-1)*w, vals, w, label=name)
    ax.bar_label(bars, fmt="%.3f", fontsize=8)
ax.set_xticks(x); ax.set_xticklabels(classes); ax.set_ylim(0, 1.05)
ax.set_title("Per-class precision / recall / f1"); ax.legend()
plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/viz5_perclass.png", dpi=150, bbox_inches="tight")
plt.show()

"""**Grad-Cam 시각화**"""

import torch
import torch.nn.functional as F
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
import glob, random, os

SAVE_DIR = "/content/drive/MyDrive/fas_project"   # 드라이브 안 쓰면 "."
os.makedirs(SAVE_DIR, exist_ok=True)

# ── 0) 모델이 메모리에 없으면 로드 ──────────────────────────
if "model" not in globals():
    from torchvision import models, transforms
    import torch.nn as nn
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    ckpt = torch.load(f"{SAVE_DIR}/best_model.pth", map_location=device)
    classes, IMG_SIZE = ckpt["classes"], ckpt["img_size"]
    model = models.efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(model.classifier[1].in_features, len(classes))
    model.load_state_dict(ckpt["model_state"])
    model = model.to(device).eval()
    eval_tf = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.ToTensor(),
        transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225]),
    ])

# ── 1) Grad-CAM 구현 ───────────────────────────────────────
class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.activations = None   # forward 시 feature map 저장
        self.gradients = None     # backward 시 gradient 저장
        target_layer.register_forward_hook(self._save_activation)
        target_layer.register_full_backward_hook(self._save_gradient)

    def _save_activation(self, module, inp, out):
        self.activations = out.detach()

    def _save_gradient(self, module, grad_in, grad_out):
        self.gradients = grad_out[0].detach()

    def __call__(self, x, class_idx=None):
        out = self.model(x)                      # 순전파
        if class_idx is None:
            class_idx = int(out.argmax(1))       # 예측 클래스 기준
        self.model.zero_grad()
        out[0, class_idx].backward()             # 해당 클래스 점수로 역전파

        # 채널별 gradient 평균 = 채널 중요도(weight)
        weights = self.gradients.mean(dim=(2, 3), keepdim=True)
        cam = (weights * self.activations).sum(dim=1).squeeze()
        cam = F.relu(cam)
        cam = cam / (cam.max() + 1e-8)           # 0~1 정규화
        return cam.cpu().numpy(), class_idx, torch.softmax(out, 1)[0].detach().cpu().numpy()

# EfficientNet-B0의 마지막 conv 블록에 hook
cam_extractor = GradCAM(model, model.features[-1])

# ── 2) 역정규화(이미지 복원용) ──────────────────────────────
def denorm(t):
    mean = np.array([0.485, 0.456, 0.406]); std = np.array([0.229, 0.224, 0.225])
    img = t.cpu().numpy().transpose(1, 2, 0) * std + mean
    return np.clip(img, 0, 1)

# ── 3) 각 클래스에서 1장씩 골라 Grad-CAM 시각화(AI 활용하여 코드 생성) ─────────────
cls_order = ["real", "print", "replay"]
picks = [(random.choice(glob.glob(f"./dataset/test/{c}/*")), c) for c in cls_order]

fig, axes = plt.subplots(2, len(picks), figsize=(5 * len(picks), 9))
for col, (path, true_label) in enumerate(picks):
    img = Image.open(path).convert("RGB")
    x = eval_tf(img).unsqueeze(0).to(device)

    cam, pred_idx, probs = cam_extractor(x)
    pred_label = classes[pred_idx]
    cam_resized = np.array(Image.fromarray((cam * 255).astype(np.uint8))
                           .resize((IMG_SIZE, IMG_SIZE))) / 255.0
    base = denorm(x[0])

    # (위) 원본
    axes[0, col].imshow(base)
    axes[0, col].set_title(f"GT: {true_label}", fontsize=12, fontweight="bold")
    axes[0, col].axis("off")

    # (아래) 원본 + 히트맵 오버레이
    axes[1, col].imshow(base)
    axes[1, col].imshow(cam_resized, cmap="jet", alpha=0.5)
    ok = (pred_label == true_label)
    color = "#2E8B57" if ok else "#D62728"
    axes[1, col].set_title(f"Grad-CAM\nPred: {pred_label} ({probs[pred_idx]*100:.1f}%)",
                           fontsize=11, color=color, fontweight="bold")
    axes[1, col].axis("off")

plt.suptitle("Grad-CAM: where the model looks", y=1.01, fontsize=14)
plt.tight_layout()
plt.savefig(f"{SAVE_DIR}/viz7_gradcam.png", dpi=150, bbox_inches="tight")
plt.show()
